### ISSUE TITLE
Loading languages in OCR settings from JSON file

### ISSUE THREAD

**Issue by irene-wilson** [Nuix/Nx#2]
Hello,
Is it by design that the languages aren't reset before loading them from a JSON file?
As a consequence, if I select English and French, but my JSON only contains English, when I load the settings it doens't remove French.
Thanks a lot for your effort on those free libraries!
Kind regards,
Irène

**Comment by JuicyDragon** [comment]
Hello Irene,
Looks like an oversight on my part.  I have a fix in place and will be pushing up the changes and a new release shortly.  Thank you for the bug report!

**Comment by JuicyDragon** [comment]
Fixed in release [v1.7.0](https://github.com/Nuix/Nx/releases/tag/v1.7.0)
