### ISSUE TITLE
[IDEA] Append Button Row in CustomTabPanel

### ISSUE THREAD

**Issue by nsiicm0** [Nuix/Nx#7]
When developing UIs for scripts using Nx, it would come in handy when we could add a row of buttons.
Right now, we have to call "appendButton" which adds one single button per row. It would be nice to add 2 (or n) buttons in a row, to make the UI more concise.

**Comment by JuicyDragon** [comment]
Hello @nsiicm0 I've made some changes that I think will provide what you are looking for.  You can download the latest release with these changes here: https://github.com/Nuix/Nx/releases/tag/v1.13.0

**Comment by nsiicm0** [comment]
Awesome! Exactly what I was looking for. Thanks!
